### ISSUE TITLE
 Support for Recurring Events

### ISSUE THREAD

**Issue by cesswairimu** [AgileVentures/LocalSupport#935]
## Planning issue for recurring events
Currently events are set for a specific date, and do not recur. It's been suggested that people might like to put repeating events in the system similar to the functionality that we have in on WebSiteOne.
[Ticket link on pivotal tracker](https://www.pivotaltracker.com/n/projects/742821/stories/151086152)

I am breaking this to be able to measure progress and submit bits by bits until its done. Anyone interested is welcome to help. :smiley: 

### SubTasks

* [ ] Add gem recurrring-select/ ice cube and add recurrence rules on the model.
* [ ]  Display recurring events on the browser + the non-recurring events.
* [ ] Add another event-like model(with a horizon)---events instances table.
* [ ] Rake task to update the "event-like" model every time an event is created/changed. Basically clears  them all and recreates them.
* [ ] Tests for the recurring events functionality
* [ ] Optimize the events instances query (maybe consider caching)

**Comment by tansaku** [comment]
this it great @cesswairimu ! btw, @NickSchimek just managed to fix our performance issue in websiteone - turns out that the ice cube gem is okay - we were just querying to many associated event-instances - seems like the storage of a horizon of events might not be necessary for performance ...?

**Comment by cesswairimu** [comment]
Aha! Awesome, Will take a look and talk to him for further info. Thanks

**Comment by NickSchimek** [comment]
Let me know if you have any questions, and/or I could help break down and explain in detail the interface ice cube provides to do event querying.

**Comment by cesswairimu** [comment]
Awesome @NickSchimek will do. Thanks

**Comment by tansaku** [comment]
@cesswairimu I wonder if we should move these tasks into pivotal tracker?  It does have the functionality and we do usually do the planning there ... but perhaps you prefer github?

**Comment by cesswairimu** [comment]
@tansaku I did not know there was a feature for the sub-tasks in pivotal tracker. Maybe that could be the best idea for this. Will take a look at the code and let you know which sub-tasks are not complete yet. Thanks
